seleniumGrid=false
gridURL=http://localhost:4444/wd/hub

#Application url
url_local = https://int.zigzag.lk/collections/gift-cards
#url_local = https://jswoneplatforms--uat.sandbox.my.site.com/
#url_local = https://demoqa.com/broken
#url_local = https://demoqa.com/browser-windows
#url_local = https://the-internet.herokuapp.com/
#url_local = https://www.abhibus.com/

#  https://www.flipkart.com

#Browser
browser = chrome

#Credentials
username =
password =

#ImplicitWait (in seconds)
implicitWait =1

#ExplicitWait
explicitWait = 3